"""init SaaS tables

Revision ID: e9ed55d79b2f
Revises: 
Create Date: 2026-08-21 21:24:47.519631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ed55d79b2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("email", sa.String(255), unique=True, nullable=False, index=True),
        sa.Column("name", sa.String(255)),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("supabase_auth_id", sa.String(36), unique=True),
        sa.Column("subscription", sa.String(20), server_default="free"),
        sa.Column("subscription_until", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "dossiers",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("project_name", sa.String(255), nullable=False),
        sa.Column("beneficiary_name", sa.String(255)),
        sa.Column("wilaya", sa.String(100)),
        sa.Column("activity_type", sa.String(100)),
        sa.Column("total_cost", sa.Integer),
        sa.Column("monthly_revenue", sa.Integer),
        sa.Column("monthly_profit", sa.Integer),
        sa.Column("status", sa.String(20), server_default="draft"),
        sa.Column("data_json", sa.JSON),
        sa.Column("content", sa.Text),
        sa.Column("pdf_r2_key", sa.String(500)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Index("ix_dossiers_tenant", "tenant_id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("dossier_id", sa.String(36), sa.ForeignKey("dossiers.id", ondelete="SET NULL")),
        sa.Column("type", sa.String(50), nullable=False),
        sa.Column("status", sa.String(20), server_default="queued"),
        sa.Column("progress", sa.Integer, server_default=sa.literal(0)),
        sa.Column("provider", sa.String(50)),
        sa.Column("result", sa.JSON),
        sa.Column("error", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Index("ix_jobs_tenant", "tenant_id"),
        sa.Index("ix_jobs_status", "status"),
    )
    op.create_table(
        "checkouts",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("plan", sa.String(20), nullable=False),
        sa.Column("billing_cycle", sa.String(20), server_default="monthly"),
        sa.Column("amount", sa.Integer, nullable=False),
        sa.Column("status", sa.String(20), server_default="pending"),
        sa.Column("gateway", sa.String(20), server_default="mock"),
        sa.Column("gateway_checkout_id", sa.String(100), unique=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Index("ix_checkouts_tenant", "tenant_id"),
    )
    # ### end Alembic commands ###
    # RLS policies — applied on Postgres after migration
    op.execute("""
        CREATE POLICY "dossiers_select_own" ON dossiers
            FOR SELECT TO anon USING (tenant_id = auth.uid());
        CREATE POLICY "dossiers_insert_own" ON dossiers
            FOR INSERT WITH CHECK (tenant_id = auth.uid());
        CREATE POLICY "jobs_select_own" ON jobs
            FOR SELECT TO anon USING (tenant_id = auth.uid());
        CREATE POLICY "jobs_insert_own" ON jobs
            FOR INSERT WITH CHECK (tenant_id = auth.uid());
        CREATE POLICY "checkouts_select_own" ON checkouts
            FOR SELECT TO anon USING (tenant_id = auth.uid());
        CREATE POLICY "checkouts_insert_own" ON checkouts
            FOR INSERT WITH CHECK (tenant_id = auth.uid());
    """)
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("checkouts")
    op.drop_table("jobs")
    op.drop_table("dossiers")
    op.drop_table("users")
    # ### end Alembic commands ###
